import { Inter } from "next/font/google";
import Link from "next/link";
// import "./globals.css";
import Links from "./component/links";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <nav>
          <ul>
            <li>
              <Link href={{ pathname: "/" }}>Home</Link>
            </li>
            <li>
              <Link href={{ pathname: "/about" }}>About</Link>
            </li>
            <li>
              <Link href={{ pathname: "/services" }}>Services</Link>
            </li>
          </ul>
        </nav> */}
        <Links/>
        {children}
        <footer>
          <h2>Footer</h2>
        </footer>
      </body>
    </html>
  );
}
